### ISSUE TITLE
[BUG]JSON format wrong?

### ISSUE THREAD

**Issue by gijbelsy** [PTST/O365Calendar-HomeAssistant#24]
When I want to parse the location data from the JSON value, HA returns nothing.
This might be due to bad JSON formatting from the sensor?

When I use the following template: 

`  {{ states.sensor.my_calendar.attributes.data }}`

HA returns the following (as expected):

`[
  {
    "subject": "The Subject",
    "body": "",
    "location": "The location",
    "categories": [],
    "sensitivity": "Normal",
    "show_as": "Busy",
    "is_all_day": false,
    "attendees": [
      "attendee1@email.com"
    ],
    "start": "2020-01-14T08:30:00+0100",
    "end": "2020-01-14T18:00:00+0100",
    "event_active": false
  }
]`

Now I want the first value, so the template becomes:
`  {{ states.sensor.my_calendar.attributes.data[0] }}`

HA returns only the first bracket ( [ ). It seems that the carriage return is causing this.

Other sensors, that don't have a CR between [ and  { work fine.

**Comment by PTST** [comment]
I have a fix worked out for this. I will post a new release later today along with an explanation

**Comment by PTST** [comment]
Please upgrade to v1.1.1 this issue has been fixed there
The problem is that the home assistant web interface does not displat attributes that are lists. So i had just serialized the json data into a string representation. So when you asked for the first item by using "\[0\]", it just returned the first character as a string. 

The data attribute is now just the raw data, but this means that home assistant just shows it as "[object][object]..." therefore i have also added the attribute "data_str_repr" that is just like the old data attribute
